@Library('My-Jenkins-SharedLibrary@dev')_

def DataBase = [:]

pipeline {
    agent any
    tools {
        jdk 'Zulu 8.76.0.17'
        maven 'Maven 3.6.3'
    }
    parameters {
        gitParameter branch: '', branchFilter: 'origin/(.*)', defaultValue: 'develop', description: '', name: 'BRANCH', quickFilterEnabled: true, selectedValue: 'DEFAULT', sortMode: 'NONE', tagFilter: '*', type: 'PT_BRANCH'
    }
    stages {
        stage("init") {
            steps {
                script {
                    sh 'env'
                    sh 'dnf install sqlite -y'
                    sh "git gc"

                    def data = serverInfoService.executeSQL(project: "local", sql: "SELECT * FROM serverinfo;")
                    List serverInfoList = serverInfoService.parseServerInfo(data)
                    Map serverInfoNameMap = serverInfoService.serverInfoNameMap(serverInfoList)

                    DataBase.put("serverInfoList", serverInfoList)
                    DataBase.put("serverInfoNameMap", serverInfoNameMap)
                }
            }
        }
        stage('git checkout') {
            steps {
                git branch: "${params.BRANCH}", credentialsId: 'd921b258-b78a-4d02-8660-30ecdf0ff70d', url: 'http://pggitlab.neutec.com.tw/sa/citixchange.git'
            }
        }
        stage('maven build') {
            steps {
                sh "mvn -v"
                sh "mvn clean package -Pdev -Dmaven.test.skip=true"
            }
        }
        stage('shutdown servers') {
            steps {
                script {
                    echo "shutdown servers"
                }
            }
        }
        stage("upload war to servers") {
            steps {
                script {
                    echo "upload war to servers"
                }
            }
        }
        stage("deploy war from servers") {
            steps {
                script {
                    echo "deploy war from servers"
                }
            }
        }
        stage("start up servers") {
            steps {
                 script {
                    echo "start up servers"
                 }
            }
        }
    }
}